owner: 4uk4uk
repo: status-page

sites:
  - name: Потребителски Интерфейс
    url: $WEBSITE_URL
  - name: Администраторски Интерфейс
    url: $ADMIN_URL
  - name: API
    url: $API_URL

status-website:
  cname: status.4uk-4uk.com
  logoUrl: https://api.4uk-4uk.com/settings/vpfns-giphy.gif
  name: Чук-Чук статус
  navbar:
    - title: Статус
      href: /
    - title: Обратно към Чук-Чук
      href: https://4uk-4uk.com

skipDescriptionUpdate: true

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"